### ISSUE TITLE
Domain - Run new repository as it own CloudFlare worker

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/w3name#2]
### Context:

As w3name is moving to its own repository and Cloudflare service, we need to create and setup how to deploy new work.

### Scope of this ticket:

* Create w3name staging and production service on DAG house Cloudflare account
* Setup domain name, dns

### Acceptance criteria:

- [ ] As a developer, I can deploy on staging and production

**Comment by mbommerez** [comment]
Decision is to go with name.web3.storage.
This has been added in the 'Routes' of the worker, but might need to do more subdomain set-up.

**Comment by francois-potato** [comment]
Done ✅ 

* https://name-staging.web3.storage/
* https://name.web3.storage/
