### ISSUE TITLE
Make `service` parameter optional in `publish` and `resolve`

### ISSUE THREAD

**Issue by adamalton** [web3-storage/w3name#21]
Currently, in the [publish](https://github.com/web3-storage/w3name/blob/c64140b0460fb11ebb49af1353d1ed4fff63f5d3/packages/client/src/index.ts#L206) and [resolve](https://github.com/web3-storage/w3name/blob/c64140b0460fb11ebb49af1353d1ed4fff63f5d3/packages/client/src/index.ts#L224) functions, we require a `service` parameter. But that service can just the default constructor parameters of the `W3NameService` class, so we could just provide that as the default and not require the `service` parameter to these two functions.

When we do this, we should also update the code in [client/example/index.js](https://github.com/web3-storage/w3name/blob/c64140b0460fb11ebb49af1353d1ed4fff63f5d3/packages/client/example/index.js).

And once we've done it, it partially unlocks #1683.

**Comment by francois-potato** [comment]
Done in #22
