### ISSUE TITLE
Review error catching

### ISSUE THREAD

**Issue by joshJarr** [web3-storage/w3name#39]
We currently don't catch errors correctly, and smother some caught issues. 

Some examples of this:
- Any non-HTTP errors are swallowed https://github.com/web3-storage/w3name/blob/8c9ea59ebe2ca99826d4da620e6e3cb5df2b3814/packages/api/src/index.ts#L36-L41
- DO Alarm errors are ignored https://github.com/web3-storage/w3name/blob/8c9ea59ebe2ca99826d4da620e6e3cb5df2b3814/packages/api/src/name.ts#L136-L138
- Some of our error messaging is too generic - we could perhaps try and return something more helpfull! https://github.com/web3-storage/w3name/blob/8c9ea59ebe2ca99826d4da620e6e3cb5df2b3814/packages/api/src/name.ts#L141

We should review ALL instances of error catching and ensure we align on how errors are returned to the user.

**Comment by mbommerez** [comment]
PR to be added to ticket.
