### ISSUE TITLE
W3name repo - switch to a organisation-wide Cloudflare token in GH

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/w3name#75]
For maintenance sake and develop experience, we'd like to switch to org-level GitHub secret for Cloudflare token for the web3.storage organisation.

Once done, we can/should remove the `CF_API_TOKEN` secret from the individual repo's secrets.

**Comment by mbommerez** [comment]
PR to switch to org level token has been merged, not deployed.
Waiting for confirmation from @hugomrdias that the `CF_API_TOKEN` secret has been deleted from this repo's secrets.

**Comment by hugomrdias** [comment]
its gone !
